# -*- coding: utf-8 -*-
"""Importacao_CSV_para_SQLite.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cDb3ivj7SIDa9p2154dfm_cwrSk3aW5Z

# Importação de Dados CSV para SQLite

## 1. Importar Bibliotecas
"""

from google.colab import files
import pandas as pd
import sqlite3
from datetime import datetime
import os

"""## 2. Configuração da Base de Dados"""

# Upload do ficheiro .db
uploaded = files.upload()

# Obter nome do ficheiro
db_file = list(uploaded.keys())[0]

# Criar conexão
conn = sqlite3.connect(db_file)
cursor = conn.cursor()

print(f"✓ Banco de dados carregado: {db_file}")

"""## 3. Carregar Dados do CSV"""

from google.colab import files
import pandas as pd

# Pedir upload do ficheiro
uploaded = files.upload()

# Obter o nome do ficheiro carregado
file_name = list(uploaded.keys())[0]

# Ler o CSV
df = pd.read_csv(file_name, sep=';')

print(f"✓ Arquivo carregado: {file_name}")
print(f"\nDimensões: {df.shape[0]} linhas × {df.shape[1]} colunas")
print(f"\nPrimeiras linhas:")
print(df.head())
print(f"\nColunas: {list(df.columns)}")
print(f"\nTipos de dados:\n{df.dtypes}")

"""## 4. Processar e Inserir Dados - Supermarket"""

# Ver colunas
print(df.columns.tolist())

# Extrair dados únicos
supermarket_df = df[['supermarket_id', 'name', 'opening_date']].drop_duplicates()

# Converter data
supermarket_df['opening_date'] = pd.to_datetime(supermarket_df['opening_date'])

# Inserir na base de dados
for _, row in supermarket_df.iterrows():
    cursor.execute('''
        INSERT OR IGNORE INTO Supermarket (supermarket_id, name, opening_date)
        VALUES (?, ?, ?)
    ''', (int(row['supermarket_id']), row['name'], row['opening_date'].date()))

conn.commit()
print(f"✓ {len(supermarket_df)} supermercado(s) inserido(s)")

"""## 5. Processar e Inserir Dados - Supplier"""

# Extrair dados únicos de Supplier
# Ajuste os nomes das colunas conforme seu CSV
supplier_df = df[['supplier_id', 'supplier_name', 'supplier_type']].drop_duplicates()

# Inserir dados na tabela Supplier
for _, row in supplier_df.iterrows():
    cursor.execute('''
        INSERT OR IGNORE INTO Supplier (supplier_id, supplier_name, supplier_type)
        VALUES (?, ?, ?)
    ''', (int(row['supplier_id']), row['supplier_name'], row['supplier_type']))

conn.commit()
print(f"✓ {len(supplier_df)} fornecedor(es) inserido(s)")

"""## 6. Processar e Inserir Dados - Department"""

# Extrair dados únicos de Department
department_df = df[['department_id', 'department_info', 'supermarket_id']].drop_duplicates().copy()

# Remover linhas onde faltem dados essenciais
department_df = department_df.dropna(subset=['department_id', 'department_info', 'supermarket_id'])

# Limpar texto
department_df['department_info'] = department_df['department_info'].astype(str).str.strip()

# Função para limpar colunas numéricas
def limpar_inteiros(serie):
    return pd.to_numeric(
        serie.astype(str)
             .str.strip()
             .str.replace(',', '.', regex=False),
        errors='coerce'
    )

# Aplicar limpeza às colunas numéricas
department_df['department_id'] = limpar_inteiros(department_df['department_id'])
department_df['supermarket_id'] = limpar_inteiros(department_df['supermarket_id'])

# Remover linhas que ficaram inválidas após conversão
department_df = department_df.dropna(subset=['department_id', 'supermarket_id'])

# Converter finalmente para inteiro
department_df['department_id'] = department_df['department_id'].astype(int)
department_df['supermarket_id'] = department_df['supermarket_id'].astype(int)

# Inserir dados na tabela Department
for _, row in department_df.iterrows():
    cursor.execute('''
        INSERT OR IGNORE INTO Department (department_id, department_info, supermarket_id)
        VALUES (?, ?, ?)
    ''', (
        row['department_id'],
        row['department_info'],
        row['supermarket_id']
    ))

conn.commit()
print(f"✓ {len(department_df)} departamento(s) inserido(s)")

"""## 7. Processar e Inserir Dados - Transation"""

# Extrair dados de Transation
transation_df = df[['supermarket_id', 'supplier_id', 'delivery_date', 'amount']].drop_duplicates().copy()

# Remover linhas com dados essenciais em falta
transation_df = transation_df.dropna(subset=['supermarket_id', 'supplier_id', 'delivery_date', 'amount'])

# Funções de limpeza
def limpar_inteiros(serie):
    return pd.to_numeric(
        serie.astype(str)
             .str.strip()
             .str.replace(',', '.', regex=False),
        errors='coerce'
    )

def limpar_decimais(serie):
    return pd.to_numeric(
        serie.astype(str)
             .str.strip()
             .str.replace(',', '.', regex=False),
        errors='coerce'
    )

# Limpar colunas numéricas
transation_df['supermarket_id'] = limpar_inteiros(transation_df['supermarket_id'])
transation_df['supplier_id'] = limpar_inteiros(transation_df['supplier_id'])
transation_df['amount'] = limpar_decimais(transation_df['amount'])

# Converter data
transation_df['delivery_date'] = pd.to_datetime(transation_df['delivery_date'], errors='coerce')

# Remover linhas inválidas após limpeza
transation_df = transation_df.dropna(subset=['supermarket_id', 'supplier_id', 'delivery_date', 'amount'])

# Converter IDs para inteiro
transation_df['supermarket_id'] = transation_df['supermarket_id'].astype(int)
transation_df['supplier_id'] = transation_df['supplier_id'].astype(int)

# Inserir dados na tabela Transation
for _, row in transation_df.iterrows():
    cursor.execute('''
    INSERT OR IGNORE INTO "Transation" (supermarket_id, supplier_id, delivery_date, amount)
    VALUES (?, ?, ?, ?)
''', (
    row['supermarket_id'],
    row['supplier_id'],
    row['delivery_date'].date(),
    float(row['amount'])
))

conn.commit()
print(f"✓ {len(transation_df)} transação(ões) inserida(s)")

"""## 8. Verificar Dados Inseridos"""

# Verificar Supermarket
print("\n=== SUPERMARKET ===")
supermarket_check = pd.read_sql_query('SELECT * FROM Supermarket', conn)
print(supermarket_check)
print(f"Total: {len(supermarket_check)} registos")

# Verificar Supplier
print("\n=== SUPPLIER ===")
supplier_check = pd.read_sql_query('SELECT * FROM Supplier', conn)
print(supplier_check)
print(f"Total: {len(supplier_check)} registos")

# Verificar Department
print("\n=== DEPARTMENT ===")
department_check = pd.read_sql_query('SELECT * FROM Department', conn)
print(department_check)
print(f"Total: {len(department_check)} registos")

# Verificar Transaction
print("\n=== TRANSACTION ===")
transation_check = pd.read_sql_query('SELECT * FROM Transation', conn)
print(transation_check)
print(f"Total: {len(transation_check)} registos")

"""## 9. Fechar Conexão"""

# Fechar conexão
conn.close()
print(f"\n✓ Conexão fechada")
print(f"✓ Banco de dados  pronto para usar!")

"""## 10. Download DB

"""

from google.colab import files

# Nome do ficheiro da base de dados
db_file = 'supermarket (2).db'

# Download
files.download(db_file)